### ISSUE TITLE
Version for Pi4 

### ISSUE THREAD

**Issue by webbaets** [cowboysdude/Pir-Sensor#4]
Launch pir.py with `sudo python3 pir.py`

For pir.py add `from subprocess import run`
and changed 'def turn_on():' and 'def turn_off():' to 
```
def turn_on():
    run('vcgencmd display_power 1',shell=True)

def turn_off():
    run('vcgencmd display_power 0',shell=True)
```
This works for me

**Comment by cowboysdude** [comment]
Thank you!  I have it working with just vcgencmd display_power 1 and vcgencmd display_power 0.  No shell needed.
